### ISSUE TITLE
UWP OAuth2Authenticator AuthenticatorPage push

### ISSUE THREAD

**Issue by fileman** [xamarin/Xamarin.Auth#177]
With Alpha 13 following the Xamarin.Forms sample, I've deleted Platform PageRenderer and use:

`
Navigation.PushAsync
                    (
                        new Xamarin.Auth.XamarinForms.AuthenticatorPage()
                        {
                            Authenticator = authenticator,
                        }
                    );
`

On Android OAuth login page was pushed, on UWP nothing happen and no exception.
Something missing in XForms UWP sample code?

**Comment by moljac** [comment]
@fileman 
Yes. Exceptions deep deep in the code. Unfortunatelly I cannot use project references, because I get "Payload contains two or more files with the same path..." for all Windows projects. And they have the same name because of nuget bait-n-switch.
Xamarin.Android and Xamarin.iOS are OK. So I need to publish nuget locally, remove refs, add again. 
And you can imagine how fast this is.

I filed a bug on VS side:
https://developercommunity.visualstudio.com/content/problem/53431/error-when-using-project-references-for-libraries.html

Try this sample I fixed it to work with 13, but needs more for sure

**Comment by fileman** [comment]
Following this sample UWP is ok, but Android seem broken.

**Comment by moljac** [comment]
@fileman 
Can you provide more info on "Android seem broken"?

**Comment by fileman** [comment]
I've open another issue (and closed), but forgot to link #178
