### ISSUE TITLE
CustomUrlSchemeInterceptor does not redirect back to app

### ISSUE THREAD

**Issue by MichelaR** [xamarin/Xamarin.Auth#213]
# Xamarin.Auth Issue

### Version

- [ ] nuget version = 4.0.0.2323
- [ ] component version = 1.5.3.0
- [ ] sample

### Steps to reproduce

1. I've created a Xamarin.Forms project with a login page, where I want to use an OAuth2Authenticator.
 
2. I created all the Events (OnCompleted etc.)

3. I've set 'isUsingNativeUI' to true (redirect_uri is : "http://localhost/callback"

4. I've created a CustomUrlSchemeInterceptor according to your examples

### Expected behavior

After successful authentication in the native browser, the interceptor should initialize the return to the app.

### Actual behaviour

I'm getting a 'this site can't be reached' in the browser and I don't get redirected to the app, but when I then choose 'open in my_app_name' or sometimes 'open in browser' the interceptor is working.. 

Do you have any ideas on why this is happening?

Thank you very much in advance!

**Comment by moljac** [comment]
@MichelaR 

This is the reason `IgaveTheClassSoooLoongName` - it needs custom scheme -  so no http and https which will be intercepted by default by system browser (Chrome with CustomTabs), so that is the reason it does not close to the app.

DISCLAIMER - it is possible to make Android to work with http/https schemes (some users did manage to do it with tweaks), but this is not documented, because this can be made to work on Android only (iOS 110% sure not)  and with tweaks. Handling all those special cases will kill my vacation and reduce my sleep from 6 hrs to 4 when I'm not on vacation. Read: too much work (code and docs) right now - it may be documented in the future.

**Comment by gonzalonm** [comment]
Any updates on this?

**Comment by newky2k** [comment]
@gonzalonm can you please try this on the latest version?

**Comment by newky2k** [comment]
no response for two weeks, closing
