### ISSUE TITLE
WebAuthenticatorPage not working with OAuth1Authenticator in UWP

### ISSUE THREAD

**Issue by Kookpot** [xamarin/Xamarin.Auth#236]
https://github.com/xamarin/Xamarin.Auth/blob/c584e5395f598b98b82bd22cfe079f135b0ffeda/source/Xamarin.Auth.UniversalWindowsPlatform/WebAuthenticatorPage.Events.xaml.cs#L28

**Comment by KoenkookpotPlasmans** [comment]
Why is there a cast here?
Don't OAuth1Authenticator and OAuth2Authenticator have a base class that exposes all necessary functions?
I tried implemented Twitter Oauth1 in UWP with with a cast exception...

**Comment by KoenkookpotPlasmans** [comment]
`var twitterAuthenticator = new OAuth1Authenticator(
                "blabla",
                "blabla",
                new Uri("https://api.twitter.com/oauth/request_token"),
                new Uri("https://api.twitter.com/oauth/authorize"),
                new Uri("https://api.twitter.com/oauth/access_token"),
                new Uri("https://auth.heapshow.com/signin-google"),
                isUsingNativeUI: true
            )
            {
                AllowCancel = false,
            };
Windows.UI.Xaml.Controls.Frame x = (Windows.UI.Xaml.Controls.Frame) Window.Current.Content;
x.Navigate(twitterAuthenticator .GetUI(), twitterAuthenticator );`

**Comment by moljac** [comment]
@KoenkookpotPlasmans 

> Why is there a cast here?
> https://github.com/xamarin/Xamarin.Auth/blob/c584e5395f598b98b82bd22cfe079f135b0ffeda/source/Xamarin.Auth.UniversalWindowsPlatform/WebAuthenticatorPage.Events.xaml.cs#L28

Because "Parameter" object passed to the target page for the navigation in UWP and its type is System.Object. And I passed OAuthXAuthenticator, so System.Object is casted on that line to OAuthXAuthenticator.


> Don't OAuth1Authenticator and OAuth2Authenticator have a base class that exposes all necessary functions?

So, I inherited this project almost accidentally and do dig through the code to understand it and refactor some things. Unfortunately most of developers that started this project are not with Xamarin anymore or are on other teams (Xamarin.Forms) and have not too much time to dive into newer version and explain some design and/or implementation decisions.

The answer would be NO few weeks ago, because since day 1 2012-10-24 both had common base class `WebAuthenticator`:

https://github.com/xamarin/Xamarin.Auth/tree/75b17c15c78fc19a6de2f33a47e58a26b459a7ab/Xamarin.Auth

Later on `WebRedirectAuthenticator` came into play and it became base class only for OAuth2Authenticator:

https://github.com/xamarin/Xamarin.Auth/commit/23b820e364a82f7e6f8eaf80ab340e158d9806cd#diff-2dd716c77da664c7a7ecc3c6dc3b0864

Today the answer is YES again, because I'm refactoring this parts, but I must be careful not to break too much.

This is bug. I must add cast and test for OAuth1Authenticator and OAuth2Authenticator.

**Comment by KoenkookpotPlasmans** [comment]
@moljac 
Thanks for the elaborate answer.
I knew there was some technical baggage build-up throughout the years.
But I'm glad you're getting on top of things! Seems like a frustrating job when there is no information available ;-).

My apologies if my ticket seemed a bit 'short' and quite direct. 

Keep up the good work!

**Comment by newky2k** [comment]
no futher action on this
