### ISSUE TITLE
Move storing Credential on another nugget with correct dependency

### ISSUE THREAD

**Issue by Phenek** [xamarin/Xamarin.Auth#266]
# Xamarin.Auth Issue
Hello Guys, I want to use Xamarin.Auth just to store credential securely, I don't need others stuff.

### Actual behaviour
I installed it on IOS and works great by using:
AccountStore.Create() etc...
But on Android:
_first I installed Xamarin.Auth package (it's throw me a Null reference exception)
_Then I got "can't load PCLCrypto.dll", so I try Installed it
but it wasn't enough I still got (Null reference exception)
_No need to call AccountStore.Create() or any method of the package to get the Null exception.
_Find out that is a problem of dependency 

### Version
- [ ] nuget version = 1.5.0.3

### Steps to reproduce

1. Create a Xamarin.Form Project
2. Install Xamarin.Auth  from nugget
3. Try to Run on Android Emulator (Fail)
4. Install PCLCrypto and his dependencies from nugget
5. Try to Run on Android Emulator (Fail)

Platform:
- [ ] VisualStudio = Mac edition up to date.
- [ ]  .NET version = Last One
- [ ]  mono version =  5.4.1.7

### Expected behaviour
Should Work like on IOS :)

Let me know,
Thanks for the package 👍

**Comment by moljac** [comment]
PCLCrypto has dependencies which cause problems in some cases. Try removing PCLCrypto, all its dependencies and Xamarin.Auth and then re-add. This helps in most cases.

Regarding 

> want to use Xamarin.Auth just to store credential securely, I don't need others stuff.

and

> AccountStore.Create()

Please update title/subject so that it really reflects the true issue (AccountStore). BTW there are already issues and merging/reopening or adding your details there would also help a lot.

"Xamarin.Auth doesn't work" does not help a lot.


BTW AccountStore will be (most likely) removed from Xamarin.Auth vNext (v.2) and moved to some other nuget. Namely OAuth does not state anything about saving.

**Comment by clovs** [comment]
Hey first thanks for your answer,

I tried to remove PCLCrypto and the re-add a lot of time,
with no result.

I don't know if I installed the correct dependency, 
there is no information about it, to make it works.

**Comment by Phenek** [comment]
[Essentials](https://github.com/xamarin/Essentials)
