### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by moljac** [xamarin/Xamarin.Auth#381]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

Repo (master and other branches).

Remove dependencies on old Cake tools which cause problems because of old stale transitive dependencies and cause Cake to crash.

Use vanilla Cake

**Comment by moljac** [comment]
Prepare Azure DevOps pipelines for building

**Comment by mahdi-ninja** [comment]
Hey guys,

Correct me if I'm wrong but Xamarin.Auth is an official project supported by the Xamarin team and apparently is not an "experimental" project or anything like that. Yet, it's been broken for quite a while now and nobody is really assigned to it. There are issues (looking at #370) that are causing problems and although are officially "Closed" but due to this build issue have never been published.

Is this really what we should expect from Xamarin team in terms of suuport?

PS: If I understand @moljac correctly, he is not officially assigned to this project and only works on it when he gets a break from his daily tasks (which I really appreciate) which means that nobody is really working on this project any more! If that's the case, can you please at least officially deprecate it?

**Comment by moljac** [comment]
@mahdi-ninja 
In 2016 I had several apps using Xamarin.Auth and Google's push to ban non-native UI gave me no choice, but to roll up my sleeves and add support for native UI. No one assigned me to any project it was simple thinking - either let library die or do something.

At that time there were people criticizing Xamarin.Auth project management and praising developers (note plural). After a long discussion and revealing that Xamarin.Auth development team consist of 1 (one) dev and that the same developer is project manager, the guy that was the loudest apologized and helped with finding schemas for facebook implementation in facebook SDK code.

Do you see the difference? He was no "senior" something, he stopped non constructive criticism and built few hours of his time into Xamarin.Auth.

Users like you cause that it is difficult to find extra motivation to keep maintaining this library and I'm not the only OSS maintainer that has the same feelings.

Closing this one.

**Comment by mahdi-ninja** [comment]
@moljac First of all, I never criticised you or any other developers and I honestly don't understand why you got so defensive about it.
My criticism was/is geared towards Xamarin/Microsoft as a company for not giving their official projects enough attention.

The point that I think you missed in my message was that the expectation from an official Xamarin/Microsoft project is different from a random OSS project that someone maintains in their spare time. When I use a random OSS project, 'm aware of the inherent risks and account for them in my time/budget and never expect project maintainers go out of their way to support my needs.

PS: My complaint is not just about this specific library. This lack of support and responsibility from Xamarin has been consistent thought out my whole experience with Xamarin products for the last 3-4 years. This has been so destructive to our business that I recently convinced my managers to rewrite a fully working Xamarin.Forms app (which took 6 month to write with a team of 4 developers) using another framework.
