### ISSUE TITLE
Username is always blank from Facebook

### ISSUE THREAD

**Issue by DavePilks** [xamarin/Xamarin.Auth#96]
I have the following code to try and authenticate via Facebook

```c#
			var auth = new OAuth2Authenticator (
				"REDACTED APP ID",
				"",
				new Uri ("https://m.facebook.com/dialog/oauth/"),
				new Uri ("http://www.facebook.com/connect/login_success.html"));

			auth.AllowCancel = true;

			auth.Completed += OAuthCompleted;

			UIViewController vc = auth.GetUI ();
```

The response is successful but the username is always blank. How can I get the username? Or even better, the email address of the user?

**Comment by marktap** [comment]
Xamarin.Auth does not get the username for you since I think that is server-specific. You can write a function to get the username and pass it as a constructor argument to OAuth2Authenticator and the authenticator will call your function after authorization is completed. The authenticator will pass your function the auth results (including the access_token). Then your code can get the username as appropriate (perhaps going back to the facebook api). The string your function returns will be used to populate the Account.Username property.
